/* Autogenerated by png2wx.pl on Tue Jan 26 10:13:07 2021 */
#ifndef BITMAP_H
#define BITMAP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_bookon_icon;

// white toolbar images
extern wxBitmap *_img_tb_w_add_bookmark;
extern wxBitmap *_img_tb_w_add_folder;
extern wxBitmap *_img_tb_w_add_item;
extern wxBitmap *_img_tb_w_find;
extern wxBitmap *_img_tb_w_open;

// black toolbar images
extern wxBitmap *_img_tb_add_bookmark;
extern wxBitmap *_img_tb_add_folder;
extern wxBitmap *_img_tb_add_item;
extern wxBitmap *_img_tb_find;
extern wxBitmap *_img_tb_open;

#endif /* BITMAP_H */
