name: Linux build

on: [ push ]

jobs:
  build:
    name: Linux build

    runs-on: ubuntu-24.04

    env:
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Conan libs
        id: cache-conan
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: /home/runner/.conan2
          key: conan-linux

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install wheel "conan>=2,<3"
          conan profile detect --force

      - name: Install system libs
        run: |
          sudo apt-get update
          
          # GTK 3.0 libraries
          sudo apt-get install libgtk-3-0 libgtk-3-dev
          sudo apt-get install libx11-xcb-dev libfontenc-dev libxaw7-dev libxmu-dev libxmuu-dev libxpm-dev libxres-dev libxss-dev
          sudo apt-get install libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev
          sudo apt-get install libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev
          sudo apt-get install libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-util-dev
          
      - name: Install libraries
        run: |
          conan install . \
            -s build_type=${{env.BUILD_TYPE}} \
            -s compiler.cppstd=17 \
            -c tools.system.package_manager:mode=install \
            -c tools.system.package_manager:sudo=True \
            --build=missing \
            -r=conancenter

      - name: Build
        run: |
          cmake --preset conan-release
          cmake --build --preset conan-release

      - name: Run tests
        run: ctest --test-dir build/${{env.BUILD_TYPE}} --output-on-failure
