name: OSX-build

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install wheel conan

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Conan Libraries
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan -f
          conan user gitlab+deploy-token-653038 -r gitlab -p sBwmejFz5Pn-gZPSNFMy
          conan install ..

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          conan build ..
          cpack -G DragNDrop

      - name: upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.dmg;bin/*.dmg;build/*.dmg"
          tags: true
          draft: true

#      - name: Run unit testing
#        run: |
#          cd ${{github.workspace}}/bin
#          ctest -V
