name: Windows-build

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    name: Windows build

    runs-on: windows-2025

    env:
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Conan libs
        id: cache-conan
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: C:/Users/runneradmin/.conan2
          key: conan-windows

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install "conan>=2,<3"
          conan profile detect --force

      - name: Install libraries
        run: |
          conan install . `
            -s build_type=${{env.BUILD_TYPE}} `
            -s compiler.cppstd=17 `
            --build=missing `
            -r=conancenter

      - name: Build
        run: |
          cmake --preset conan-release
          cmake --build --preset conan-release --config ${{env.BUILD_TYPE}}

      - name: CPack
        working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
        run: |
          cpack -C ${{env.BUILD_TYPE}} -G ZIP

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{github.workspace}}/build/${{env.BUILD_TYPE}}/*.zip

  upload_all:
    name: Upload if release
    needs: [build]
    runs-on: ubuntu-24.04
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Upload to releases
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.zip;dist/*.msi"
          tags: true
          draft: true
          verbose: true
