name: Windows-build

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    name: Windows build

    runs-on: windows-2022

    env:
      BUILD_TYPE: RelWithDebInfo
      CPPSTD: 17
      CONAN_CONFIGURE_PRESET: conan-default
      CONAN_BUILD_PRESET: conan-relwithdebinfo
      BUILD_DIR: ${{github.workspace}}/cmake-build/build
      PROJ_LIB: ${{github.workspace}}/cmake-build/build/bin

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Cache Conan libs
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan2-${{ runner.os }}-${{ runner.arch }}-${{ env.BUILD_TYPE }}-cppstd${{ env.CPPSTD }}-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            conan2-${{ runner.os }}-${{ runner.arch }}-${{ env.BUILD_TYPE }}-cppstd${{ env.CPPSTD }}-
            conan2-${{ runner.os }}-${{ runner.arch }}-

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install "conan>=2,<3"
          conan profile detect --force

      - name: Install libraries
        run: |
          conan install . 
           --output-folder=${{github.workspace}}/cmake-build 
           --build=missing 
           -s build_type=${{env.BUILD_TYPE}} 
           -s:h compiler.cppstd=${{env.CPPSTD}}
           -s:b compiler.cppstd=${{env.CPPSTD}}
           -r=conancenter

      - name: Configure
        run: cmake --preset ${{env.CONAN_CONFIGURE_PRESET}}

      - name: Build
        run: cmake --build --preset ${{env.CONAN_BUILD_PRESET}}

      - name: Installer ZIP
        working-directory: ${{env.BUILD_DIR}}
        run: cpack -G ZIP -C ${{env.BUILD_TYPE}}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{env.BUILD_DIR}}/*.zip
            ${{env.BUILD_DIR}}/bin/*.pdb
            ${{env.BUILD_DIR}}/bin/${{env.BUILD_TYPE}}/*.pdb
          retention-days: 5

  upload_all:
    name: Upload if release
    needs: [build]
    runs-on: ubuntu-24.04
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: artifact
          path: dist

      - name: Upload to releases
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.zip;dist/*.msi;dist/bin/bookon.pdb"
          tags: true
          draft: true
          verbose: true
